include gruvbox-dark.conf

font_family      Hack Nerd Font Mono
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic
font_size 12

hide_window_decoration yes
background_opacity 1.0
enable_audio_bell no
